Adding jks support in tidb MR connector
tidb-incubator/TiBigData pull request #123
Opened 2021-12-14 01:59 UTC by ankita25

Currently only pem files are supported. This code adds support to jks

2021-12-14 02:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tidb-incubator/TiBigData?pullRequest=123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tidb-incubator/TiBigData?pullRequest=123) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ankita25<br/>:x: Ankita Wagh<br/><hr/>**Ankita Wagh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tidb-incubator/TiBigData?pullRequest=123) it.</sub>

2021-12-14 06:30 UTC, sunxiaoguang commented
Hi @ankita25, thanks for your contribution. Could you please verify if binary compiled with upgraded Hadoop version works with previous Hadoop version. From the changes it looks like they might be binary compatible. If that's the case maybe we can simply change dependency to provided and you can use whatever version you would like in production.

2021-12-17 20:55 UTC, ankita25 commented
> Hi @ankita25, thanks for your contribution. Could you please verify if binary compiled with upgraded Hadoop version works with previous Hadoop version. From the changes it looks like they might be binary compatible. If that's the case maybe we can simply change dependency to provided and you can use whatever version you would like in production.

I didn't mean to merge the hadoop changes. Let me remove them .. Thank you

2021-12-18 15:29 UTC, sunxiaoguang commented
You can click on details link to find out why CI failed. 
For example this link:https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tibigdata_ghpr_build/detail/tibigdata_ghpr_build/415/pipeline/

2021-12-20 13:30 UTC, sunxiaoguang commented
/run-all-tests

2021-12-21 06:58 UTC, ankita25 commented
Is the integration test progressing ?

2021-12-21 07:01 UTC, sunxiaoguang commented
you can write a comment like this '/run-all-tests' to trigger all tests

2021-12-21 07:01 UTC, sunxiaoguang commented
/run-all-tests

2021-12-21 13:51 UTC, sunxiaoguang reviewed
I'm wondering is it possible to add test for this new feature?

2021-12-21 13:51 UTC, sunxiaoguang commented on mapreduce/mapreduce-base/src/main/java/io/tidb/bigdata/mapreduce/tidb/TiDBConfiguration.java
> +
There are two empty spaces in this line

2021-12-21 18:59 UTC, ankita25 commented
/run-all-tests

2021-12-21 19:00 UTC, ankita25 commented
> I'm wondering is it possible to add test for this new feature?

hmm I didn't see many tests for map reduce connector

2021-12-22 04:18 UTC, ankita25 commented
> I'm wondering is it possible to add test for this new feature?

The tests passed this time.

2021-12-22 13:27 UTC, sunxiaoguang commented
> 
Sorry that I didn't make it clear. I know that existing code doesn't have enough tests, but we do hope it can get better over time. Therefore I asked if it is possible to add test to new code. If this feature can only be verified with integration test, we have to at least make sure it's tested manually.

2021-12-22 19:29 UTC, ankita25 commented
> > 
> 
> Sorry that I didn't make it clear. I know that existing code doesn't have enough tests, but we do hope it can get better over time. Therefore I asked if it is possible to add test to new code. If this feature can only be verified with integration test, we have to at least make sure it's tested manually.

yeah I did verify it manually
`

21/12/10 23:47:38 INFO mapreduce.Job: Job job_1639179006043_0006 running in uber mode : false
--
21/12/10 23:47:38 INFO mapreduce.Job:  map 0% reduce 0%
21/12/10 23:47:45 INFO mapreduce.Job:  map 100% reduce 0%
21/12/10 23:47:46 INFO mapreduce.Job: Job job_1639179006043_0006 completed successfully
21/12/10 23:47:46 INFO mapreduce.Job: Counters: 30
File System Counters
FILE: Number of bytes read=0
FILE: Number of bytes written=206810
FILE: Number of read operations=0
FILE: Number of large read operations=0
FILE: Number of write operations=0
HDFS: Number of bytes read=162
HDFS: Number of bytes written=0
HDFS: Number of read operations=1
HDFS: Number of large read operations=0
HDFS: Number of write operations=0
Job Counters
Launched map tasks=1
Other local map tasks=1
Total time spent by all maps in occupied slots (ms)=4836
Total time spent by all reduces in occupied slots (ms)=0
Total time spent by all map tasks (ms)=4836
Total vcore-milliseconds taken by all map tasks=4836
Total megabyte-milliseconds taken by all map tasks=4952064
Map-Reduce Framework
Map input records=1
Map output records=0
Input split bytes=162
Spilled Records=0
Failed Shuffles=0
Merged Map outputs=0
GC time elapsed (ms)=169
CPU time spent (ms)=9940
Physical memory (bytes) snapshot=306319360
Virtual memory (bytes) snapshot=2078961664
Total committed heap usage (bytes)=187695104
File Input Format Counters
Bytes Read=0
File Output Format Counters
Bytes Written=0
`
Test command - 
JAVA_HOME="/usr/lib/jvm/openjdk8" CLASSPATH=/usr/share/java/mysql-connector-java-8.0.25.jar /mnt/awagh/hadoop-2.10.0/bin/hadoop jar ~/mapreduce-tidb-connector-base-0.0.7-SNAPSHOT-PINTEREST.jar io.tidb.bigdata.mapreduce.tidb.example.TiDBMapreduceDemo  -du "jdbc:mysql://10.3.0.167:4000/test" -clusterTls  -clusterUseJks -clusterJksKeyPath <PATH> -clusterJksKeyPassword <PASSWORD> -clusterJksTrustPath <PATH> -clusterJksTrustPassword <PASSWORD>  -u  root  -p  ""  -dn test  -t test_table

2021-12-23 16:28 UTC, ankita25 commented
Any more concerns?

2021-12-24 00:40 UTC, sunxiaoguang commented on mapreduce/mapreduce-base/src/main/java/io/tidb/bigdata/mapreduce/tidb/TiDBConfiguration.java
> +  public static final String CLUSTER_JKS_TRUST_PATH = "tidb.jks.trust_path";
All configuration items uses dash however `trust_path` uses underscore instead. We should make it consistent.

2021-12-24 00:44 UTC, sunxiaoguang requested changes
Rest LGTM

2021-12-24 00:45 UTC, sunxiaoguang commented
> 

Cool, thanks for your contribution. I left a comment about configuration key naming convention. Please take a look and that is the only comment I have.

2021-12-24 01:30 UTC, sunxiaoguang commented
> Any more concerns?

Sorry, was busy training yesterday and didn't have chance to look at this PR.

2021-12-27 18:40 UTC, ankita25 commented
/run-all-tests

2021-12-28 00:25 UTC, ankita25 commented
> Cool, thanks for your contribution. I left a comment about configuration key naming convention. Please take a look and that is the only comment I have.

updated. thanks

2021-12-28 01:12 UTC, sunxiaoguang approved these changes

2021-12-28 01:13 UTC, merged