Rewrite filter pushdown
tidb-incubator/TiBigData pull request #158
Opened 2022-03-07 12:26 UTC by humengyu2012

Do not merge this PR, because there are some documents to write.

2022-03-08 06:53 UTC, humengyu2012 commented
> Do not merge this PR, because there are some documents to write.

Docs was added.

2022-03-08 06:54 UTC, humengyu2012 commented
/run-all-tests

2022-03-09 07:07 UTC, shiyuhang0 commented
/run-all-tests

2022-03-09 10:06 UTC, humengyu2012 commented
/run-all-tests

2022-03-09 10:20 UTC, humengyu2012 commented
/run-all-tests

2022-03-21 04:57 UTC, xuanyu66 requested changes

2022-03-21 05:47 UTC, humengyu2012 commented on flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/table/FilterPushDownHelper.java
> +  // We use empty as placeholder, which may cause the range of filters to become larger.
Placeholder can be anything, and empty can help us deal with it without forgetting.

2022-03-21 06:12 UTC, humengyu2012 commented on flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/table/FilterPushDownHelper.java
> +    // which means that 'CAST' syntax will be ignored, please use '`c1` = CAST(1 AS INT)'.
There is no expression of `cast` for tikv. If we want support expression like `'CAST(`c1` as int) = 1'`, we must cast 1 as        `c1.datatype`, it is not a good idea which may cause errors.

2022-03-21 06:16 UTC, humengyu2012 commented on flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/table/FilterPushDownHelper.java
> +    final DataType valueType = valueElement.getType();
Reserved for new feature, such as set, enum and json. But these types are not supported now by tikv.

2022-03-21 06:17 UTC, humengyu2012 commented on flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/table/FilterPushDownHelper.java
> +  private final TiTableInfo tiTableInfo;
I am not sure whether we will need it in the future, so i decide to reserve it.

2022-03-21 06:32 UTC, humengyu2012 commented
/run-all-tests

2022-03-22 02:38 UTC, xuanyu66 approved these changes

2022-03-22 07:17 UTC, sunxiaoguang approved these changes

2022-03-22 07:17 UTC, merged