Add TLS to TiBigDate/Flink
tidb-incubator/TiBigData pull request #195
Opened 2022-05-17 07:14 UTC by Daemonxiao

## What does this PR solve?
 Add TLS support to TiBigData Flink connector with TiDB cluster.

## How does it work?

TiBigData supports enabling TLS when connecting with a TiDB cluster. If you want to fully enable TLS, you need to enable TLS for JDBC and TiKV-client respectively.

### JDBC TLS

To enable JDBC TLS in TiBigData, just add the TLS configuration to the `tidb.database.url` configuration.

### TiKV-Client TLS
Currently, TiKV-Client supports two specified certificate conifgurations:

1. An X.509 certificate collection in PEM format needs three configurations.
  - tidb.cluster-tls-ca
  - tidb.cluster-tls-key
  - tidb.cluster-tls-cert
2. A JKS store with four configurations.
  - tidb.cluster-jks-enable
  - tidb.cluster-jks-key-path
  - tidb.cluster-jks-key-password
  - tidb.cluster-jks-trust-path
  - tidb.cluster-jks-trust-password

### What does this PR do?

* Add libnetty_tcnative
* Add README.md
* Add TLS test github action

2022-05-19 09:42 UTC, Daemonxiao commented
/run-all-tests

2022-06-07 15:19 UTC, Daemonxiao commented
/run-all-tests

2022-06-09 08:35 UTC, xuanyu66 requested changes

2022-06-09 08:35 UTC, xuanyu66 commented on flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/tls/TiKVSourceTLSTest.java
> +public class TiKVSourceTLSTest {
Add this test to flink-1.13

2022-06-09 12:33 UTC, Daemonxiao commented on flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/tls/TiKVSourceTLSTest.java
> +public class TiKVSourceTLSTest {
OK

2022-06-09 14:06 UTC, zhangyangyu approved these changes

2022-06-13 06:44 UTC, xuanyu66 approved these changes

2022-06-15 07:04 UTC, shiyuhang0 approved these changes

2022-06-15 07:25 UTC, Daemonxiao commented on flink/README.md
> +| tidb.cluster-tls-enable                     | false                                                                          | Whether to enable TLS between TiBigData and TLS.
@shiyuhang0 Thanks for your review. I'll correct it.

2022-06-16 02:37 UTC, Daemonxiao commented
/run-all-tests

2022-06-16 04:53 UTC, xuanyu66 commented
/run-all-tests

2022-06-16 05:31 UTC, merged