fix type convert
tidb-incubator/TiBigData pull request #224
Opened 2022-06-23 07:21 UTC by shiyuhang0

## What is the purpose of the change
close #223

## Brief change log

- fix the TiDBRowConverter.toTiRow:  the error type convert will throw ClassCastException 
- fix the decode：Object to long will throw ClassCastException

## Verifying this change

_ an IT has been added

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: ( no)
- The runtime per-record code paths (performance sensitive): (yes)

## Documentation

- Does this pull request introduce a new feature? (no)

2022-06-23 07:51 UTC, xuanyu66 commented on tidb/src/main/java/io/tidb/bigdata/tidb/codec/RowEncoderV2.java
> +        encodeInt(cdo, Long.parseLong(value.toString()));
Can we remove .toString()

2022-06-23 11:36 UTC, shiyuhang0 commented
/run-all-tests

2022-06-28 03:10 UTC, xuanyu66 requested changes

2022-06-28 03:10 UTC, xuanyu66 commented on flink/flink-1.14/src/test/java/io/tidb/bigdata/flink/tidb/sink/TiKVSinkTypeTest.java
> +@Category(IntegrationTest.class)
Change to Streaming group

2022-06-28 04:58 UTC, shiyuhang0 commented
/run-all-tests

2022-06-28 05:15 UTC, shiyuhang0 commented
/run-all-tests

2022-06-28 05:20 UTC, xuanyu66 commented
Since it's a performance-sensitive change. 
https://jenkov.com/tutorials/java-performance/jmh.html

2022-06-29 11:06 UTC, shiyuhang0 commented
/run-all-tests

2022-06-29 14:04 UTC, xuanyu66 commented
/run-all-tests

2022-06-30 02:58 UTC, shiyuhang0 commented
/run-all-tests

2022-07-01 06:23 UTC, xuanyu66 approved these changes

2022-07-01 06:37 UTC, humengyu2012 approved these changes

2022-07-04 05:02 UTC, shiyuhang0 commented
/run-all-tests

2022-07-04 05:53 UTC, merged