CDC ignore column case
tidb-incubator/TiBigData pull request #257
Opened 2022-11-16 19:36 UTC by humengyu2012

## What is the purpose of the change

Ignore column case in CDC.

## Brief change log

1. Change column name to lower case in craft and json.
2. Use CDC original column name in canal-json.

## Verifying this change

Use current tests.

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency):  no
- The public API: no
- The runtime per-record code paths (performance sensitive): yes

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-11-16 19:37 UTC, humengyu2012 commented
https://github.com/tidb-incubator/TiBigData/issues/250

2022-11-17 02:40 UTC, xuanyu66 requested changes
Plz add some tests

2022-11-17 02:40 UTC, xuanyu66 commented on flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/format/cdc/TiDBCanalJsonDeserializationSchema.java
> +  private static final String FIELD_DATA = "data";
unused field

2022-11-17 06:35 UTC, humengyu2012 commented
/run-all-tests

2022-11-18 02:49 UTC, xuanyu66 approved these changes

2022-11-18 03:13 UTC, xuanyu66 commented on flink/flink-1.13/src/test/java/io/tidb/bigdata/flink/format/cdc/TiDBCanalJsonDeserializationSchemaTest.java
> +    // jsonDeserializer should be only changed once
What do you mean here？

2022-11-18 03:53 UTC, xuanyu66 requested changes
Plz add some comments

2022-11-20 10:32 UTC, humengyu2012 commented
/run-all-tests

2022-11-21 14:50 UTC, xuanyu66 approved these changes

2022-11-22 07:34 UTC, merged